dist: xenial
services:
  - docker
language: node_js
node_js:
  - "8"
  # - "10"
before_script:
  - npm install -g gulp-cli
script: gulp  
deploy:
  - provider: script
    script: bash ./build/deploy.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      branch: master
      tags: true